### ISSUE TITLE
Qmanager configuration?

### ISSUE THREAD

**Issue by ptrovatelli** [AATools/mq-metrics-pyclient#9]
Hello,
I can't find where the qmanagers are supposed to be configured. Do we need to hardcode it in `mq_managers_data` variable?  Are remote qmanagers supported? 

Thanks!

**Comment by woblerr** [comment]
Hi,

The metrics are collected from  **all local** mq managers. So, you need to run `mq_metrics_client` in the same host where IBM MQ server installed.

The metrics are collected by using standard MQSC commands. For example, the list of mq managers  is obtained by `dspmq` command. Other commands: [#L8-L19](https://github.com/AATools/mq-metrics-pyclient/blob/ec340b5280032a0319c28f7ad335de5209f5b7b9/modules/mq_api.py#L8-L19).

You can put metrics to local or remote Prometheus pushgateway (`--pghost` and `--pgport` parameters need).

Remote mq managers currently isn't supported.

Probably, this is not clear from the documentation, we will think how to update it. Thanks!

Do we need to add the ability to set specific managers for metric collecting?

**Comment by ptrovatelli** [comment]
ok thanks it is clearer. I hadn't realized that MQSC commands couldn't be done remotely.

**Comment by woblerr** [comment]
MQSC commands can be issued on a remote queue manager. 
For this, the remote queue manager must be correctly configured. 
IBM documentation: https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.adm.doc/q021120_.html

Anyway, we added to our documentation that metrics are collected for local queue managers.

**Comment by ptrovatelli** [comment]
yes but you'd still need to run the utility on a VM with an MQ server installed.
